packageExtensions:
  "@midnight-ntwrk/wallet-sdk-node-client@*":
    dependencies:
      "@polkadot/api-base": "16.5.4"
  "@midnight-ntwrk/wallet-sdk-facade@*":
    dependencies:
      "effect": "^3.20.0"
